### ISSUE TITLE
frida-trace FileMonitor

### ISSUE THREAD

**Issue by fopina** [frida/frida-tools#2]
`FileMonitor` does not seem to be triggering under MacOSX (Sierra), so handlers are not reloaded when files are updated.

I couldn't really debug into it so I updated my tracer to use https://pythonhosted.org/watchdog/ which is a common package, cross-platform, heavily used/tested.

Is this a PR that could be of interest?

**Comment by oleavr** [comment]
Frida's `FileMonitor` is simply exposing [GLib](https://gitlab.gnome.org/GNOME/glib/)'s [GLib.FileMonitor](https://developer.gnome.org/gio/stable/GFileMonitor.html). As GLib is at the base of Frida's tech stack it's great to use components already there. I noticed there's recently been massive quality improvements to the i/macOS backend in GLib upstream, so I suspect this problem will disappear next time we rebase our patches on the latest upstream. I'm about to update the SDKs, so now is a good time to do this. I'll keep you posted.

**Comment by fopina** [comment]
Makes perfect sense, I’ll look it up and give it a try as well then thanks!

This was more of a question than an actual issue (though there is an issue indeed :)) so feel free to close it if you want to keep this list clean
