### ISSUE TITLE
Feature: option to disable terminal colors (colorama)

### ISSUE THREAD

**Issue by arizvisa** [frida/frida-tools#7]
would be friendly to have an option or environment variable to disable the usage of colorama so that terminal escape sequences aren't emitted. this way colors aren't imposed on the user and they have a choice.

**Comment by oleavr** [comment]
PR welcome!

**Comment by arizvisa** [comment]
it was easier to just remove it entirely. i can submit a PR that gets rid of the colorama dependency, but i figure since you guys did the work to add coloring that it would be contrary to your guys original intentions.

writing code sucks, but if i submit a PR will you actually merge it?

**Comment by oleavr** [comment]
Yes if it's a PR adding an option to disable it.

**Comment by arizvisa** [comment]
PR #8.

**Comment by arizvisa** [comment]
Re-opened so it's more apparent how this was mishandled.

**Comment by oleavr** [comment]
Let's keep tracking this in #8.
